title: IATI RSS Feeds
description: The missing RSS feeds for various IATI websites.

collections:
  iati_connect:
    sort_by: order
    output: false

  iati_connect_comments:
    sort_by: order
    output: false

  iati_standard:
    sort_by: order
    output: false
