name: Fetch feeds

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '30 * * * *'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate data
        run: |
          python app.py
        env:
          GITHUB_PAGES: TRUE
          CONNECT_USERNAME: ${{ secrets.CONNECT_USERNAME }}
          CONNECT_PASS: ${{ secrets.CONNECT_PASS }}
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: public
          single-commit: true
          token: ${{ secrets.GH_TOKEN }}
          git-config-name: Code for IATI bot
          git-config-email: 57559326+codeforIATIbot@users.noreply.github.com
